---
- name: Provisioning and Deploying spring pet clinic into docker through ansible
  hosts: dev
  become: yes
  tasks:
    - name: Install Docker & python
      yum:
        name:
          - docker
          - python-pip
        state: present
      
    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
        
    - name: Running Docker Container
      docker_container:
        name: sprinGpeTcliniC
        image: satish200691/springpetclinic:{{DOCKER_TAG}}
        state: started
        published_ports: 0.0.0.0:9000:9000
